import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import dotenv from "dotenv";
import ReduxProvider from "@/redux/reduxProvider";
import AuthWrapper from "@/lib/AuthWrapper"; // client wrapper
import { SocketProvider } from "@/lib/SocketContext";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/contexts/ThemeContext";

dotenv.config();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Closer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-neutral-900 text-neutral-900 dark:text-white transition-colors duration-300`}
      >
        <ThemeProvider>
          <GoogleOAuthProvider clientId={`${process.env.GOOGLE_CLIENT_ID}`}>
            <ReduxProvider>
              <SocketProvider>
                <AuthWrapper>{children}</AuthWrapper>
                <Toaster />
              </SocketProvider>
            </ReduxProvider>
          </GoogleOAuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
